module.exports = {
  operation: {
    perform: {
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer {{bundle.authData.api_key}}',
      },
      params: {
        status: '{{bundle.inputData.status}}',
        product_id: '{{bundle.inputData.product_id}}',
        product_variant_id: '{{bundle.inputData.product_variant_id}}',
        as_array: 'true',
      },
      removeMissingValuesFrom: { params: true, body: true },
      url: 'https://app.jetform.id/api/v1/orders',
    },
    inputFields: [
      {
        key: 'status',
        label: 'Order Status',
        helpText: 'Filter by order status',
        type: 'string',
        choices: ['pending', 'paid', 'expired', 'cancelled', 'free'],
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'product_id',
        type: 'string',
        label: 'ID Produk',
        required: false,
        list: false,
        altersDynamicFields: true,
      },
      {
        key: 'product_variant_id',
        type: 'string',
        label: 'ID Varian Produk',
        required: false,
        list: false,
        altersDynamicFields: true,
      },
    ],
    type: 'polling',
    canPaginate: false,
    sample: {
      id: 'dcf12444-6d8e-4f88-83b2-f8abdfcf624f',
      status: 'paid',
      total: 149000,
      invoice_number: '240224-44920',
      valid_until: '2024-02-24T09:03:44Z',
      inserted_at: '2024-02-24T07:03:44Z',
      updated_at: '2024-02-24T07:14:54Z',
      user_id: '436cf950-da72-4b2b-9604-e82263e85a76',
      product_id: 'bb3343f0-5031-4ca8-9829-d2c4c014833a',
      customer_name: 'Eka Putra',
      service_fee: 7450,
      paid_at: '2024-02-24T07:14:54Z',
      product_name: 'Ebook - Zero to Programmer',
      product_variant_name: 'Versi E-BOOK + AUDIO BOOK + Konsultasi',
      customer_email: 'ekaputra07@gmail.com',
      customer_phone: '081339512507',
      discount_name: null,
      discount_value: 0,
      payment_type: 'bank_transfer',
      product_variant_id: '90b1fd6f-e462-4642-add7-62657faaf911',
      sub_total: 149000,
    },
    outputFields: [
      { key: 'id', type: 'string' },
      { key: 'status', type: 'string' },
      { key: 'total', type: 'integer' },
      { key: 'invoice_number', type: 'string' },
      { key: 'valid_until', type: 'datetime' },
      { key: 'inserted_at', type: 'datetime' },
      { key: 'updated_at', type: 'datetime' },
      { key: 'user_id', type: 'string' },
      { key: 'product_id', type: 'string' },
      { key: 'customer_name', type: 'string' },
      { key: 'service_fee', type: 'integer' },
      { key: 'paid_at', type: 'datetime' },
      { key: 'product_name', type: 'string' },
      { key: 'product_variant_name', type: 'string' },
      { key: 'customer_email', type: 'string' },
      { key: 'customer_phone', type: 'string' },
      { key: 'discount_name', type: 'string' },
      { key: 'discount_value', type: 'integer' },
      { key: 'payment_type', type: 'string' },
      { key: 'product_variant_id', type: 'string' },
      { key: 'sub_total', type: 'integer' },
    ],
  },
  display: {
    description: 'Triggers when a new order is created.',
    hidden: false,
    label: 'New Order',
  },
  key: 'new_order',
  noun: 'Order',
};
